steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx:4.2.0
    settings:
      repo: registry-local.devops.svc.cluster.local/rojandincse
      tags: git-${CI_COMMIT_SHA:0:4}
      dockerfile: Dockerfile
      buildkit_config: |
        [registry."registry-local.devops.svc.cluster.local"]
          http = true
          insecure = true
    when:
      - event: [push]

  - name: deploy-preview-env
    image: pelotech/drone-helm3
    settings:
      mode: install
      namespace: apps
      chart: ./chart
      release: "web-${CI_COMMIT_SOURCE_BRANCH}"
      skip_tls_verify: true
      values: "image.tag=git-${CI_COMMIT_SHA:0:4},ingress.hosts[0].host=${CI_COMMIT_SOURCE_BRANCH}.rojandinc.se,ingress.annotations.external-dns.alpha.kubernetes.io/hostname=${CI_COMMIT_SOURCE_BRANCH}.rojandinc.se"
      values_files:
        - "environment/preview.yaml"
      api_server:
        from_secret: api_server
      kubernetes_token:
        from_secret: kubernetes_token
    depends_on: [publish]
    when:
      - event: [pull_request]
        branch:
          exclude: main

  - name: deploy-preview-env
    image: pelotech/drone-helm3
    settings:
      mode: uninstall
      namespace: apps
      release: "web-${CI_COMMIT_SOURCE_BRANCH}"
      skip_tls_verify: true
      api_server:
        from_secret: api_server
      kubernetes_token:
        from_secret: kubernetes_token
    when:
      - event: [pull_request_closed]
        branch:
          exclude: main

  - name: deploy
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      namespace: apps
      chart: ./chart
      release: web
      skip_tls_verify: true
      values: "image.tag=git-${CI_COMMIT_SHA:0:4}"
      values_files:
        - "environment/values.yaml"
      api_server:
        from_secret: api_server
      kubernetes_token:
        from_secret: kubernetes_token
    depends_on: [publish]
    when:
      - event: [push]
        branch: [main]

