steps:
  - name: build-dry-run
    image: woodpeckerci/plugin-docker-buildx:4.2.0
    settings:
      dry-run: true
      repo: registry.home/rojandincse
      tags: git-${CI_COMMIT_SHA:0:4}
      dockerfile: Dockerfile
    when:
      - event: [pull_request]
        branch:
          exclude: main
  - name: publish
    image: woodpeckerci/plugin-docker-buildx:4.2.0
    settings:
      repo: registry.home/rojandincse
      tags: git-${CI_COMMIT_SHA:0:4}
      dockerfile: Dockerfile
      logins:
        - registry: https://registry.rojandinc.se
          mirrors:
            - registry.home
    when:
      - event: [push]
        branch: [main]
  - name: deploy
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      namespace: apps
      release: rojandincse
      add_repos: ["rojandinc=https://rojandinc.github.io/helm-charts"]
      chart: rojandinc/web
      chart_version: 0.2.0
      skip_tls_verify: true
      values: "image.tag=git-${CI_COMMIT_SHA:0:4}"
      values_files:
        - "environment/values.yaml"
      api_server:
        from_secret: api_server
      kubernetes_token:
        from_secret: kubernetes_token
    depends_on: [publish]
    when:
      - event: [push]
        branch: [main]
